### ISSUE TITLE
tokenization_utils_base.py", line 3450, in _pad     encoded_inputs["attention_mask"] = encoded_inputs["attention_mask"] + [0] * difference OverflowError: cannot fit 'int' into an index-sized integer

### ISSUE THREAD

**Issue by zsszyx** [JackChen890311/Simple-Magic-Animate#3]
`Traceback (most recent call last):
  File "inference.py", line 24, in <module>
    main(args.image, args.motion, args.seed, args.steps, args.guidance_scale)
  File "inference.py", line 10, in main
    animation = animator(reference_image, motion_sequence_path, seed, steps, guidance_scale)
  File "/media/sda/zsy/Simple-Magic-Animate-main/Simple-Magic-Animate-main/magic-animate/demo/animate.py", line 157, in __call__
    sample = self.pipeline(
  File "/home/lab225/anaconda3/envs/zsy/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/media/sda/zsy/Simple-Magic-Animate-main/Simple-Magic-Animate-main/magic-animate/magicanimate/pipelines/pipeline_animation.py", line 592, in __call__
    text_embeddings = self._encode_prompt(
  File "/media/sda/zsy/Simple-Magic-Animate-main/Simple-Magic-Animate-main/magic-animate/magicanimate/pipelines/pipeline_animation.py", line 187, in _encode_prompt
    text_inputs = self.tokenizer(
  File "/home/lab225/anaconda3/envs/zsy/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2602, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/home/lab225/anaconda3/envs/zsy/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2688, in _call_one
    return self.batch_encode_plus(
  File "/home/lab225/anaconda3/envs/zsy/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2879, in batch_encode_plus
    return self._batch_encode_plus(
  File "/home/lab225/anaconda3/envs/zsy/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 744, in _batch_encode_plus
    batch_outputs = self._batch_prepare_for_model(
  File "/home/lab225/anaconda3/envs/zsy/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 816, in _batch_prepare_for_model
    batch_outputs = self.pad(
  File "/home/lab225/anaconda3/envs/zsy/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3086, in pad
    outputs = self._pad(
  File "/home/lab225/anaconda3/envs/zsy/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3450, in _pad
    encoded_inputs["attention_mask"] = encoded_inputs["attention_mask"] + [0] * difference
OverflowError: cannot fit 'int' into an index-sized integer
`

**Comment by zsszyx** [comment]
Traceback (most recent call last):
  File "inference.py", line 24, in <module>
    main(args.image, args.motion, args.seed, args.steps, args.guidance_scale)
  File "inference.py", line 10, in main
    animation = animator(reference_image, motion_sequence_path, seed, steps, guidance_scale)
  File "/media/sda/zsy/Simple-Magic-Animate-main/Simple-Magic-Animate-main/magic-animate/demo/animate.py", line 157, in __call__
    sample = self.pipeline(
  File "/home/lab225/anaconda3/envs/zsy/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/media/sda/zsy/Simple-Magic-Animate-main/Simple-Magic-Animate-main/magic-animate/magicanimate/pipelines/pipeline_animation.py", line 592, in __call__
    text_embeddings = self._encode_prompt(
  File "/media/sda/zsy/Simple-Magic-Animate-main/Simple-Magic-Animate-main/magic-animate/magicanimate/pipelines/pipeline_animation.py", line 187, in _encode_prompt
    text_inputs = self.tokenizer(
  File "/home/lab225/anaconda3/envs/zsy/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2602, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/home/lab225/anaconda3/envs/zsy/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2688, in _call_one
    return self.batch_encode_plus(
  File "/home/lab225/anaconda3/envs/zsy/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 2879, in batch_encode_plus
    return self._batch_encode_plus(
  File "/home/lab225/anaconda3/envs/zsy/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 744, in _batch_encode_plus
    batch_outputs = self._batch_prepare_for_model(
  File "/home/lab225/anaconda3/envs/zsy/lib/python3.8/site-packages/transformers/tokenization_utils.py", line 816, in _batch_prepare_for_model
    batch_outputs = self.pad(
  File "/home/lab225/anaconda3/envs/zsy/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3086, in pad
    outputs = self._pad(
  File "/home/lab225/anaconda3/envs/zsy/lib/python3.8/site-packages/transformers/tokenization_utils_base.py", line 3450, in _pad
    encoded_inputs["attention_mask"] = encoded_inputs["attention_mask"] + [0] * difference
OverflowError: cannot fit 'int' into an index-sized integer

**Comment by JackChen890311** [comment]
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way

**Comment by zsszyx** [comment]
I just dont' know how to deal with "encoded_inputs["attention_mask"] = encoded_inputs["attention_mask"] + [0] * difference
OverflowError: cannot fit 'int' into an index-sized integer". I try different projects, official, unofficial，the same question happened. No offense, I feel it's a problem with the text prompt, but I don't know how to customize the prompt.

**Comment by JackChen890311** [comment]
Since I did not encounter this error, I would suggest you to reproduce [Magic Animate](https://github.com/magic-research/magic-animate) first. It's possible that this issue comes from your environment or package version. Sorry I couldn't provide more useful information as this seems to be a problem from the original github repository.

**Comment by zsszyx** [comment]
Thanks
